### ISSUE TITLE
cargo: KeyError 'blurmac'

### ISSUE THREAD

**Issue by okias** [flatpak/flatpak-builder-tools#181]
Cargo.lock is from https://github.com/servo/servo/ project.
```
python3 ./flatpak-cargo-generator.py Cargo.lock -o cargo-sources.json             [15:55:49]

WARNING:root:background_hang_monitor has no source
WARNING:root:bluetooth has no source
WARNING:root:bluetooth_traits has no source
INFO:root:Loading packages from git https://github.com/servo/devices
Traceback (most recent call last):
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 222, in <module>
    main()
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 217, in main
    generated_sources = generate_sources(load_toml(args.cargo_lock))
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 149, in generate_sources
    git_sources, cargo_vendored_entry = get_git_sources(package)
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 113, in get_git_sources
    pkg_subpath = git_cargo_packages[name]
KeyError: 'blurmac'
```

**Comment by gasinvein** [comment]
This is because `blurmac` package in https://github.com/servo/devices is just stored in-tree, while we currently only handle workspaces in git repos. I'm not yet sure how we should handle this, but you can try this quick-and-dirty fix:
```patch
diff --git a/cargo/flatpak-cargo-generator.py b/cargo/flatpak-cargo-generator.py
index 69c1fb2..0c9c4bd 100755
--- a/cargo/flatpak-cargo-generator.py
+++ b/cargo/flatpak-cargo-generator.py
@@ -71,6 +71,14 @@ def get_git_cargo_packages(git_url, commit):
                 with open(subpkg_toml, 'r') as s:
                     pkg_toml = toml.loads(s.read())
                 packages[pkg_toml['package']['name']] = subpkg
+    for subproj_toml in glob.glob(os.path.join(git_repo_dir, '**', 'Cargo.toml'), recursive=True):
+        subpkg = os.path.relpath(os.path.dirname(subproj_toml), git_repo_dir)
+        logging.debug(f'Found package {subpkg}')
+        with open(subproj_toml, 'r') as s:
+            pkg_toml = toml.loads(s.read())
+        if 'package' not in pkg_toml:
+            continue
+        packages[pkg_toml['package']['name']] = subpkg
     logging.debug(f'Packages in repo: {packages}')
     return packages
 
```

**Comment by okias** [comment]
Generator passed, currently flatpak-builder does nothing with the cargo-sources.json file

```
flatpak-builder --repo=repo org.servo.Servo data/org.servo.Servo.json --force-clean                                                                                                                      [15:27:57]

(flatpak-builder:25305): Json-CRITICAL **: 15:27:57.794: json_gobject_deserialize: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed

(flatpak-builder:25305): Json-WARNING **: 15:27:57.796: Failed to deserialize "modules" property of type "gpointer" for an object of type "BuilderManifest"
Emptying app dir 'org.servo.Servo'
Downloading sources
Starting build of org.servo.Servo
Cache hit for cleanup, skipping
Cache miss, checking out last cache hit
Finishing app
Error: Command 'servo' not found
```

**Comment by gasinvein** [comment]
How does the whole manifest look like?

**Comment by okias** [comment]
http://sprunge.us/KH7sdR

**Comment by gasinvein** [comment]
This is the generated-sources file contents. How do you add it to the app manifest?

**Comment by okias** [comment]
https://github.com/okias/servo/commit/310e489ba0b334b83e1f47ac4dd6f17649f630ca#diff-04cc61a783a70dda48b99e5a69e6e8ae434c71e5c3fc71564211c01addb00f22R25

**Comment by gasinvein** [comment]
This is incorrect. The generated file contains sources, so you're supposed to add it a module sources list. See e.g. [this](https://github.com/flathub/net.veloren.veloren/blob/70aacde6e3ed49039040edea7daff7dc410d06fb/net.veloren.veloren.yaml#L62) as an example.

**Comment by okias** [comment]
Thank you, is somehow possible to sed all paths to have it in /app/... ... cargo/

was thinking about ` sed "s|cargo/|/app/cargo" data/cargo-sources.json` since I'm using currently `CARGO_HOME=/app`

**Comment by okias** [comment]
So generally original issue is solved, that sed worked.

But it seems that builder-tools missed mio dependency
```
  failed to load source for dependency `mio`
```

**Comment by okias** [comment]
Latest file, it started again failing on raqote: http://sprunge.us/AgGCyN

**Comment by gasinvein** [comment]
The [manifest](https://github.com/okias/servo/blob/ad5c0dfadfd9e198edaaf94ecb51cfbc42e4205b/data/org.servo.Servo.json) is still incorrect, `"cargo-sources.json"` should be listed among `servo` module sources, and `CARGO_HOME` should point to `/run/build/servo/cargo`. Please see other Rust apps on Flathub to get examples.

**Comment by okias** [comment]
Currently everything works with your quick&dirty fix.

**Comment by gasinvein** [comment]
I need someone familiar with rust/cargo to confirm that this is valid project repository layout.

@bilelmoussaoui @muelli @alatiera The rust package https://github.com/servo/devices stores `blurmac` subpackage in-tree, without using workspace. Is such layout legit for rust packages?

**Comment by okias** [comment]
Ok, it does still works for me with that patch. Can I make a MR from it? (just for being able to patch flatpak-builder-tools automated way.

**Comment by gasinvein** [comment]
Sure, if it helps, although please mark it as draft until it's properly tested and confirmed to be working for packages with other (more common) layouts.
