### ISSUE TITLE
flatpak-pip-generator fails for python-dateutil package

### ISSUE THREAD

**Issue by ssssam** [flatpak/flatpak-builder-tools#53]
I generated a manifest for the 'python-dateutil' package. flatpak-builder failed to build it, with the following error:

```
Looking in links: file:///run/build/python3-dateutil
Collecting python-dateutil
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3.7 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-d9lhe25f --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links file:///run/build/python3-dateutil -- "setuptools; python_version != '3.3'" "setuptools<40.0; python_version == '3.3'" wheel setuptools_scm:
  Ignoring setuptools: markers 'python_version == "3.3"' don't match your environment
  Looking in links: file:///run/build/python3-dateutil
  Collecting setuptools
    Could not find a version that satisfies the requirement setuptools (from versions: )
  No matching distribution found for setuptools
```

I'm building against the GNOME 3.32 platform, which does have setuptools already installed. However, notice that pip is being passed `--ignore-installed` which may be causing it to be ignored.

I worked around this issue by adding 'wheel' and 'setuptools_scm' to the list of packages needed, and by commenting out the line in flatpak-pip-generator that skips the 'setuptools' package. Including those 3 modules in the list of sources for python-dateutil led to a successful build.

**Comment by TingPing** [comment]
Um, the script doesn't add `--ignore-installed` so I'm not sure where that is coming from?

**Comment by barthalion** [comment]
`Ignoring setuptools: markers 'python_version == "3.3"' don't match your environment`

Doesn't it mean that dateutil requires setuptools version which works only on Python 3.3?

**Comment by ssssam** [comment]
The full line is: `"setuptools; python_version != '3.3'" "setuptools<40.0; python_version == '3.3'"`, I don't know exactly what that means but I think it's a conditional dependency o

I should note, that this problem happens against the org.gnome.Sdk/x86_64/3.32 runtime. Perhaps it's a new issue in that version of the runtime? I'll try building against an older version.

**Comment by ssssam** [comment]
The same issue occurs with 3.30.

I think the real issue here might be that python-dateutil expresses a dependency on setuptools_scm [in its `setup_requires`](https://github.com/dateutil/dateutil/blob/master/setup.cfg#L33). Apparently pip doesn't download setup_requires dependencies, it leaves that to setuptools instead. So this could be why `pip download` doesn't get the full set of dependencies needed by the python-dateutil package.

The workaround for this issue is straightforward, but it would be better if there was a way to actually get the full set of dependencies for a package without manually figuring them out.

**Comment by biswasab** [comment]
I am facing the exact same issue while trying to use manifest for cryptography.

**Comment by nolyn** [comment]
I ran into a similar problem. For me dateutil was pulled in by matplotlib. I also had a similar problem with pytest. 
I can resolve it by adding --no-build-isolation, i.e.
```
{
    "name": "python3-python-dateutil",
    "buildsystem": "simple",
    "build-commands": [
        "pip3 install --no-index  --no-build-isolation --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} python-dateutil"
    ],
    "sources": [
        {
            "type": "file",
            "url": "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz",
            "sha256": "d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
        },
        {
            "type": "file",
            "url": "https://files.pythonhosted.org/packages/ad/99/5b2e99737edeb28c71bcbec5b5dda19d0d9ef3ca3e92e3e925e7c0bb364c/python-dateutil-2.8.0.tar.gz",
            "sha256": "c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e"
        }
    ]
}
```
I also found this, it might be related: https://github.com/dateutil/dateutil/issues/840, installing dateutil 2.7.0 worked.
My problem occurred when changing from kde platform 5.11 (python 3.5) to 5.12 (python 3.7).

**Comment by vancha** [comment]
I don´t know if this is useful information, but flatpak-pip-generator not being able to successfully generate the modules for datuetils, also makes it not work for implementing mastodon.py. 
When  a "python flatpak-pip-generator mastodon.py" is executed, the resulting modules can be made working when nolyn´s fix is used: changing dateutils version to 2.7.0:
{
                "type": "file",
                "url": "https://files.pythonhosted.org/packages/e5/1d/64a3b1c30842ecf0518af93ed123e5064559e588aebdcae0a59831dee642/python-dateutil-2.7.0.tar.gz",
                "sha256": "8f95bb7e6edbb2456a51a1fb58c8dca942024b4f5844cae62c90aa88afe6e300"
            }

Hope this helps someone out :)

**Comment by danyeaw** [comment]
I can't reproduce this issue with the latest master version. I think this is fixed by #63, since python-dateutil is now installed using the wheel.

```
(.env) dan@dan-Librem-13-v2:~/Projects/flatpak-builder-tools/pip$ python flatpak-pip-generator python-dateutil
Collecting python-dateutil
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-python-dateutil-082sa1df/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-python-dateutil-082sa1df/six-1.12.0-py2.py3-none-any.whl
Successfully downloaded python-dateutil six
Generating hash for /tmp/pip-generator-python3-python-dateutil-082sa1df/python_dateutil-2.8.0-py2.py3-none-any.whl
Extracting download url for python_dateutil
Generating hash for /tmp/pip-generator-python3-python-dateutil-082sa1df/six-1.12.0-py2.py3-none-any.whl
Extracting download url for six
```

```
{
    "name": "python3-python-dateutil",
    "buildsystem": "simple",
    "build-commands": [
        "pip3 install --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} python-dateutil"
    ],
    "sources": [
        {
            "type": "file",
            "url": "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl",
            "sha256": "7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb"
        },
        {
            "type": "file",
            "url": "https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl",
            "sha256": "3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c"
        }
    ]
}
```

**Comment by ragreenburg** [comment]
For what it is worth, this problem still exists and doesn't seem to have been fixed by the merge request listed above, sadly.
